data:
  data_dir: "data/interiornet/HD2/3FO4KFWYFQW8"

generation:
  prompt:
    HD2_3FO4KFWYFQW8: magic lit, sci-fi RGB glowing, studio lighting
  
  frame_range: [250, 550, 1]

base_config: configs/interiornet/iclight_interiornet_vidtome.yaml