data:
  data_dir: "data/interiornet/HD3/3FO4KAUK7D3T"

generation:
  prompt:
    HD3_3FO4KAUK7D3T: This video showcases a modern, open-concept living space featuring a living room and kitchen.

  frame_range: [0, 300, 1]

base_config: configs/interiornet/iclight_interiornet_vidtome.yaml