data:
  data_dir: "data/interiornet/HD4/3FO4KDJXMRCO"

generation:
  prompt:
    HD4_3FO4KDJXMRCO: This video showcases a modern interior space, which is dimly lit.
  
  frame_range: [250, 550, 1]

base_config: configs/interiornet/iclight_interiornet_vidtome.yaml