data:
  data_dir: "data/interiornet/HD6/3FO4JVTCFV05"

generation:
  prompt:
    HD6_3FO4JVTCFV05: A modern living room, pink light, romantic, girlish

  frame_range: [250, 550, 1]

base_config: plugin/VidToMe/configs/interiornet/iclight_interiornet_vidtome.yaml