work_dir: "workdir/examples"

data:
  rgb_path: "examples/navsim.mp4"
  height: 536       # Must be divisible by 8
  width: 960        # Must be divisible by 8
  fps: 15

generation:
  alpha_t: 0.0      # Disable decayed multi-axis denoising
  frame_range: [0, -1, 1]
  prompt:
    navsim: The video captures a busy urban street scene with multiple 
             vehicles. The sky is clear, indicating a warm, sunny day.

base_config: configs/tclight_default.yaml