data:
  data_dir: "data/carla/sim2real_2_6/data_collect_town01_results"
  scene_name: "routes_town01_02_06_20_45_19"

generation:
  prompt:
    routes_town01_02_06_20_45_19: The video depicts a late evening scene of a car driving on a well-lit road.
    
base_config: configs/carla/iclight_carla_vidtome.yaml