data:
  data_dir: "data/carla/sim2real_2_6/data_collect_town05_results"
  scene_name: "routes_town05_04_09_17_59_26"
  
generation:
  prompt:
    routes_town05_04_09_17_59_26: The video depicts a late evening scene of a car driving on a well-lit road.

base_config: plugin/VidToMe/configs/carla/iclight_carla_vidtome.yaml