work_dir: "workdir/carla/iclight_vidtome"

data:
  scene_type: "carla"  # 'sceneflow' or ...
  height: 536
  width: 960
  fps: 15

generation:
  prompt_upsampler_ckpt: "/data2/yang_liu/Cosmos/checkpoints/Pixtral-12B"
  negative_prompt: "The video captures a game playing, with bad crappy graphics and cartoonish frames. It represents a recording of old outdated games. The lighting looks very fake. The textures are very raw and basic. The geometries are very primitive. The images are very pixelated and of poor CG quality. There are many subtitles in the footage. Overall, the video is unrealistic at all."

  # VidToMe args. See details in "src/vidtome/patch.py, apply_patch()"
  local_merge_ratio: 0.9
  global_merge_ratio: 0.8
  frame_range: [0, 300, 1] # start, end, interval. == [0, 32] == [32]

  alpha_t: 0.0

seed: 123
base_config: plugin/VidToMe/configs/iclight_default.yaml