work_dir: "workdir/carla/iclight_vidtome_slicedit_opt"

data:
  alpha: 0.75
  apply_mask: False
  voxel_size: 0.05

generation:
  alpha_t: 0.01

post_opt:
  apply_opt: True
  lambda_dssim: 0.4

base_config: plugin/VidToMe/configs/carla/iclight_carla_vidtome.yaml