work_dir: "workdir/agibot/iclight_vidtome_slicedit_opt_highres"

data:
  height: 720
  width: 960

generation:
  negative_prompt: "lowres, bad anatomy, bad hands, cropped, digital rendering, 3D rendering, computer rendering, virtual, worst quality"

  alpha_t: 0.0

  # VidToMe args. See details in "src/vidtome/patch.py, apply_patch()"
  local_merge_ratio: 0.9
  global_merge_ratio: 0.8
  frame_range: [0, -1, 2] # start, end, interval. == [0, 32] == [32]

post_opt:
  apply_opt: False

base_config: configs/agibot/iclight_agibot_vidtome.yaml