foreground_conditioned_examples = [
    [
        "imgs_iclight/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Right Light",
        512,
        960,
        12345,
        "imgs_iclight/o1.png",
    ],
    [
        "imgs_iclight/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Left Light",
        512,
        960,
        50,
        "imgs_iclight/o2.png",
    ],
    [
        "imgs_iclight/i3.png",
        "beautiful woman, detailed face, neon, Wong Kar-wai, warm",
        "Left Light",
        512,
        768,
        12345,
        "imgs_iclight/o3.png",
    ],
    [
        "imgs_iclight/i3.png",
        "beautiful woman, detailed face, sunshine from window",
        "Left Light",
        512,
        768,
        12345,
        "imgs_iclight/o4.png",
    ],
    [
        "imgs_iclight/i5.png",
        "beautiful woman, detailed face, warm atmosphere, at home, bedroom",
        "Left Light",
        512,
        768,
        123,
        "imgs_iclight/o5.png",
    ],
    [
        "imgs_iclight/i6.jpg",
        "beautiful woman, detailed face, sunshine from window",
        "Right Light",
        512,
        768,
        42,
        "imgs_iclight/o6.png",
    ],
    [
        "imgs_iclight/i7.jpg",
        "beautiful woman, detailed face, shadow from window",
        "Left Light",
        512,
        768,
        8888,
        "imgs_iclight/o7.png",
    ],
    [
        "imgs_iclight/i8.webp",
        "beautiful woman, detailed face, sunset over sea",
        "Right Light",
        512,
        640,
        42,
        "imgs_iclight/o8.png",
    ],
    [
        "imgs_iclight/i9.png",
        "handsome boy, detailed face, neon light, city",
        "Left Light",
        512,
        640,
        12345,
        "imgs_iclight/o9.png",
    ],
    [
        "imgs_iclight/i10.png",
        "beautiful woman, detailed face, light and shadow",
        "Left Light",
        512,
        960,
        8888,
        "imgs_iclight/o10.png",
    ],
    [
        "imgs_iclight/i11.png",
        "Buddha, detailed face, sci-fi RGB glowing, cyberpunk",
        "Left Light",
        512,
        768,
        8888,
        "imgs_iclight/o11.png",
    ],
    [
        "imgs_iclight/i11.png",
        "Buddha, detailed face, natural lighting",
        "Left Light",
        512,
        768,
        12345,
        "imgs_iclight/o12.png",
    ],
    [
        "imgs_iclight/i13.png",
        "toy, detailed face, shadow from window",
        "Bottom Light",
        512,
        704,
        12345,
        "imgs_iclight/o13.png",
    ],
    [
        "imgs_iclight/i14.png",
        "toy, detailed face, sunset over sea",
        "Right Light",
        512,
        704,
        100,
        "imgs_iclight/o14.png",
    ],
    [
        "imgs_iclight/i15.png",
        "dog, magic lit, sci-fi RGB glowing, studio lighting",
        "Bottom Light",
        512,
        768,
        12345,
        "imgs_iclight/o15.png",
    ],
    [
        "imgs_iclight/i16.png",
        "mysteriou human, warm atmosphere, warm atmosphere, at home, bedroom",
        "Right Light",
        512,
        768,
        100,
        "imgs_iclight/o16.png",
    ],
]

bg_samples = [
    'imgs_iclight/bgs/1.webp',
    'imgs_iclight/bgs/2.webp',
    'imgs_iclight/bgs/3.webp',
    'imgs_iclight/bgs/4.webp',
    'imgs_iclight/bgs/5.webp',
    'imgs_iclight/bgs/6.webp',
    'imgs_iclight/bgs/7.webp',
    'imgs_iclight/bgs/8.webp',
    'imgs_iclight/bgs/9.webp',
    'imgs_iclight/bgs/10.webp',
    'imgs_iclight/bgs/11.png',
    'imgs_iclight/bgs/12.png',
    'imgs_iclight/bgs/13.png',
    'imgs_iclight/bgs/14.png',
    'imgs_iclight/bgs/15.png',
]

background_conditioned_examples = [
    [
        "imgs_iclight/alter/i3.png",
        "imgs_iclight/bgs/7.webp",
        "beautiful woman, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs_iclight/alter/o1.png",
    ],
    [
        "imgs_iclight/alter/i2.png",
        "imgs_iclight/bgs/11.png",
        "statue of an angel, natural lighting",
        "Use Flipped Background Image",
        512,
        768,
        12345,
        "imgs_iclight/alter/o2.png",
    ],
    [
        "imgs_iclight/alter/i1.jpeg",
        "imgs_iclight/bgs/2.webp",
        "beautiful woman, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs_iclight/alter/o3.png",
    ],
    [
        "imgs_iclight/alter/i1.jpeg",
        "imgs_iclight/bgs/3.webp",
        "beautiful woman, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs_iclight/alter/o4.png",
    ],
    [
        "imgs_iclight/alter/i6.webp",
        "imgs_iclight/bgs/15.png",
        "handsome man, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs_iclight/alter/o5.png",
    ],
]
