data:
  rgb_path: "data/navsim/sensor_blobs/trainval/2021.06.09.17.23.18_veh-38_00305_00597/CAM_F0"

generation:
  prompt:
    navsim_38_00305_00597: The video depicts a nighttime city street scene.  Streetlights and traffic signals illuminate the area, casting a cyberpunk hue on the road.

base_config: plugin/VidToMe/configs/navsim/iclight_navsim_vidtome.yaml