data:
  rgb_path: "data/navsim/sensor_blobs/trainval/2021.06.23.17.31.36_veh-16_00634_01421/CAM_F0"

generation:
  prompt:
    navsim_16_00634_01421: The video captures a busy urban street scene with multiple vehicles. The sky is clear, indicating a warm, sunny day.

base_config: plugin/VidToMe/configs/navsim/iclight_navsim_vidtome.yaml