data:
  rgb_path: "data/waymo/kitti_format/training/image_0/648"

inversion:
  save_path: "${work_dir}/648/latents"

generation:
  prompt:
    waymo_648: The video depicts a quiet residential street lined with parked cars on both sides. The atmosphere is overcast, contributing to the overall gloomy weather.

base_config: configs/waymo/iclight_waymo_vidtome.yaml