data:
  rgb_path: "data/waymo/kitti_format/training/image_0/642"

inversion:
  save_path: "${work_dir}/642/latents"

generation:
  prompt:
    # waymo_642: A city street at dusk, bathed in the soft glow of streetlights and building lights. The sky is a gradient of twilight, indicating the transition from day to night.
    waymo_642: cyberpunk city street at midnight, sci-fi RGB glowing, illuminated the soft glow of neon lights and building lights

base_config: configs/waymo/iclight_waymo_vidtome.yaml