data:
  rgb_path: "data/waymo/kitti_format/training/image_0/492"

inversion:
  save_path: "${work_dir}/492/latents"

generation:
  prompt:
    waymo_492: A city street covered by snow. The sky is clear and blue, suggesting a calm, sunny day.

base_config: configs/waymo/iclight_waymo_vidtome.yaml