data:
  rgb_path: "data/rvt/real/press_sanitizer/video.mp4"

generation:
  background_cond: True
  background_image_path: "data/rvt/real/backgrounds/background_01"
  prompt:
    press_sanitizer: living room, robotic arm on the table, bright

base_config: configs/rvt/tclight_agibot_vidtome.yaml