data:
  rgb_path: "data/rvt/real/put_object_in_drawer/video.mp4"

generation:
  background_cond: True
  background_image_path: "data/rvt/real/backgrounds/background_02"
  prompt:
    put_object_in_drawer: living room, robotic arm on the table, bright

base_config: configs/rvt/tclight_agibot_vidtome.yaml