data:
  rgb_path: "data/scand/A_Spot_Dobie_Dobie_Thu_Nov_11_73.avi"

generation:
  prompt:
    A_Spot_Dobie_Dobie_Thu_Nov_11_73: Wong Kar-wai, warm

base_config: configs/scand/iclight_scand_vidtome.yaml