data:
  rgb_path: "data/scand/B_Spot_Speedway_SAC_Wed_Nov_10_48.avi"

generation:
  prompt:
    B_Spot_Speedway_SAC_Wed_Nov_10_48: at dusk, bathed in the soft glow of streetlights
      and building lights

base_config: plugin/VidToMe/configs/scand/iclight_scand_vidtome.yaml