work_dir: "workdir/interiornet/iclight_vidtome_slicedit_opt_highres"

data:
  height: 720  # should be divisible by 8
  width: 960  # should be divisible by 8
  voxel_size: 0.005
  apply_mask: False

generation:
  negative_prompt: "lowres, bad anatomy, bad hands, cropped, digital rendering, 3D rendering, computer rendering, virtual, worst quality."
  alpha_t: 0.01

post_opt:
  apply_opt: True

base_config: configs/interiornet/iclight_interiornet_vidtome.yaml