data:
  rgb_path: "data/drone/drone_2"

generation:
  prompt:
    drone_2: In autumn, the leaves turn golden and red, creating a beautiful landscape.

base_config: plugin/VidToMe/configs/drone/iclight_drone_vidtome.yaml