generation:
  prompt:
    15mm_bk_left: "The road is wet, the atmosphere is overcast, contributing to the overall rainy weather." 

base_config: plugin/VidToMe/configs/sceneflow/iclight_sceneflow_vidtome.yaml