work_dir: "path/to/your/work_dir"

data:
  scene_type: "video"
  # rgb_path: "path/to/your/video"
  height: 720       # Must be divisible by 8
  width: 960        # Must be divisible by 8
  fps: 25

generation:
  negative_prompt: >
    The video captures a game playing, with bad crappy graphics and cartoonish frames.
    It represents a recording of old outdated games. The lighting looks very fake.
    The textures are very raw and basic. The geometries are very primitive.
    The images are very pixelated and of poor CG quality. There are many subtitles
    in the footage. Overall, the video is unrealistic at all.
  
  prompt_upsampler_ckpt: "path/to/Cosmos/checkpoints/Pixtral-12B"   # if use hand-crafted prompt, ignore it
  prompt: null
    # style: "xxx"
    # object: "xxx"
    # background: "xxx"

  frame_range: [0, -1, 2]        # [start, end, interval]
  save_frame: true

  alpha_t: 0.0                   # 0.01 is a good default value if need decayed multi-axis denoising

post_opt:
  apply_opt: true
  epochs_exposure: 35
  epochs: 70
  batch_size: 16
  lambda_dssim: 0.2              # Increase to better match denoised result
  lambda_flow: 0.8               # Increase to enhance motion consistency
  lambda_tv: 0.05                # Increase to smooth adjacent pixels

seed: 123
base_config: configs/tclight_default.yaml