work_dir: "workdir"  # directory to save outputs and intermediate results, change it as you like

data:
  scene_type: "video"
  rgb_path: "path/to/your/video"  # path to your video file, change it as you like
  height: 720  # should be divisible by 8
  width: 960  # should be divisible by 8
  fps: 15

generation:
  negative_prompt: "The video captures a game playing, with bad crappy graphics and cartoonish frames. It represents a recording of old outdated games. The lighting looks very fake. The textures are very raw and basic. The geometries are very primitive. The images are very pixelated and of poor CG quality. There are many subtitles in the footage. Overall, the video is unrealistic at all."

  prompt: null
    # style: "xxx"
    # object: "xxx"
    # background: "xxx"

  frame_range: [0, -1, 1]  # start, end, interval. -1 means the last frame. == [0, -1] == all frames
  save_frame: True

  alpha_t: 0.0  # set it to positive value to apply decayed multi-axis denoising, a good value is 0.01

post_opt:
  apply_opt: True  # You can set it to False to skip post optimization
  epochs_exposure: 35  # Number of epochs for exposure optimization
  epochs: 70  # Number of epochs for unique video tensor optimization
  batch_size: 16  # Batch size for optimization, lower it if you have limited GPU memory
  lambda_dssim: 0.2  # Weight to balance dssim loss, increase it to better align with relighting result
  lambda_flow: 0.8  # Weight to balance flow loss, increase it to enhance motion consistency
  lambda_tv: 0.05  # Weight to balance total variation loss, increase it to enhance smoothness among adjacent pixels

seed: 123
base_config: configs/tclight_default.yaml