data:
  rgb_path: "data/agibot_digital/observations/digitaltwin_5/1e01900f-798b-467f-bf60-e227c3ae3073/video/head.mp4"

generation:
  prompt:
    # agibot_digitaltwin_5_upsampled: "The video depicts a robotic arm performing a task on a wooden table. The robot, equipped with a gripper, interacts with various objects including a green bowl, a yellow box, a small card, and a green block. The scene is set near a window, allowing natural light to illuminate the workspace. The robotic arm carefully picks up and manipulates the objects, demonstrating precision and control in a simulated environment."
    agibot_digitaltwin_5: "The video depicts a robotic arm performing a task on a wooden table. The scene is set near a window, allowing natural light to illuminate the workspace. The robotic arm carefully picks up and manipulates the objects, demonstrating precision and control" 

base_config: plugin/VidToMe/configs/agibot/iclight_agibot_vidtome.yaml