data:
  rgb_path: "data/agibot_digital/observations/digitaltwin_1/aada330e-73e3-4d05-90a6-ff6fa83b5b23/video/head.mp4"

generation:
  prompt:
    # agibot_digitaltwin_1_upsampled: 'The image depicts a modern television set placed on a wooden entertainment center. The TV is mounted on a sleek, black stand with a minimalist design. The entertainment center features two gold-framed compartments, adding a touch of elegance to the setup. The background wall has a textured, light-colored finish, complementing the overall contemporary aesthetic of the room.'
    agibot_digitaltwin_1: "at home, living room, a modern television, robotic arm" 

base_config: configs/agibot/iclight_agibot_vidtome.yaml