work_dir: "workdir/scand/iclight_vidtome_slicedit_opt_highres"

data:
  height: 720  # should be divisible by 8
  width: 1280  # should be divisible by 8

generation:
  alpha_t: 0.01

post_opt:
  apply_opt: True

base_config: configs/scand/iclight_scand_vidtome.yaml